### ISSUE TITLE
Unable to remove button from Main Toolbar

### ISSUE THREAD

**Issue by bgiesing** [kyxap/koreader-calibre-plugin#21] opened 2024-05-05 18:20 UTC
Every other Calibre plugin and internal function I can add and remove just fine but for some reason after adding KOreader Sync to the main toolbar (as prompted when first installing it), it throws an error and is impossible to remove
![image](https://github.com/harmtemolder/koreader-calibre-plugin/assets/7895463/a3f4e3cb-fb0d-48c1-bd89-4da92f7b7b89)

calibre: version 7.10.0
Windows 11

**Comment by kyxap** [comment] 2024-05-30 13:19
Is this still an issue? Can you provide steps to reproduce?
Everything works for me just fine:


![remove](https://github.com/harmtemolder/koreader-calibre-plugin/assets/3080529/04ed9b87-5b34-485d-be19-f2e3549e5885)

**Comment by kyxap** [comment] 2024-07-27 17:14
closing as author have not answered and I was not able to reproduce

**Closed as completed by kyxap** 2024-07-27 17:14 UTC
Labels: unable to reproduce
